### PR TITLE
Update Sponsor brochure. Add Tango Hackathon to home. Revert home.png image change.

### PR DESCRIPTION
**Pull request by miketraverso**
Michael, added back the home (reduced size). Also added a counter for the Tango hackathon. Will need to write up a blog post for that this week.

### CODE REVIEW

**Comment by Splaktar** [comment]
OK, that sounds good. Can you make a card in Trello with some of the info that you got from the Project Tango team?

**Comment by Splaktar** [comment]
Should we remove the Code Lab counters then?

**Comment by miketraverso** [comment]
No. We can up that counter probably and just have the hackathon space also be a space for folks to work out code labs if that’s what they’re interested in. What do you think of that idea?

**Comment by Splaktar** [comment]
I think that if we do code labs, we need experts there to help people when they run into problems. I don't think that we'll just want a space for them to run the Google code labs (they have a lot of bugs and updates bring breaking changes... often the day before the event).

**Comment by miketraverso** [comment]
OK

**Comment by Splaktar** [comment]
Once we get some speakers confirmed, I think that we can ask them about their interest in helping with these code labs. But it might not be a great experience without a separate code lab room or time. Will the hackathon go the full day?

**Pull request merged**
