### PR TITLE
Minor

### PR DESCRIPTION
**Pull request by miketraverso**

### CODE REVIEW

**Comment by Splaktar** [comment]
Hrm, I spent a lot of time last night getting the home image positioned correctly and getting the image size down to bring the website from 15 MBs to 5 MBs. This seems to reverse some of that work.

**Comment by miketraverso** [comment]
I can alter the image to redo that work but this is a much better image. It's also not Cutting off the logo and text. When I check the site the logo is cut off and it just doesn't look right. This new image is pretty high res so I'll update it to reduce the size.

**Comment by Splaktar** [comment]
I removed the logo from the image. I guess you were looking at an old version.

**Comment by Splaktar** [comment]
I want to keep the nav from being on top of lights/buildings as it makes it hard to read and use. Ideally the top left DevFest Florida logo should not be on top of lights/buildings either.

## Smaller Screens

screen shot 2016-08-08 at 1 50 21 pm
screen shot 2016-08-08 at 1 50 35 pm

I think that the logo and text (if we keep them) of the `home` image need to be smaller so as not to get clipped on larger screens like below.

## Larger Screens

screen shot 2016-08-08 at 1 50 43 pm
screen shot 2016-08-08 at 1 50 55 pm

**Pull request merged**
